export const data = [
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["a Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["b Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["c Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["d Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["e Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["f Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["g Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["h Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["i Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["j Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["k Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["l Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["m Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["n Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["o Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["p Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["q Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["r Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"],
	["Saya suka <strong>main bola</strong>", "Saya main <strong>boneka</strong>", "Saya main layangan"]
]